name: mcp-excel
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pandas>=2.2.3
  - openpyxl>=3.1.5
  - mcp[cli]>=1.3.0
  - pytest>=8.0.0
  - pytest-cov>=4.1.0
  - black>=24.1.0
  - isort>=5.13.0
  - mypy>=1.8.0
  - pip
  - pip:
    - hatchling>=1.21.0 